### ISSUE TITLE
Adding News items in a publisher/stakeholder friendly way

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#101]
**What:**
Enable Drought stakeholders to post news items on the Drought homepage (https://drought.ca.gov/) and Newsroom (https://drought.ca.gov/newsroom/) in a user friendly manner that lay persons can use.

* No HTML or HTML copy/paste
* Add / update "post" in Wordpress and then the news items shows automatically on the homepage and /newsroom pages. Or 
* (Ideally) functionally preview to ensure content is as expected before publishing

**Why:**
We want to begin handing off publishing to our stakeholders to lessen dependency on ODI. News content is the main priority to start with as it's updated with greater frequency and has minimal ODI content design/copy edits. Thus, empowering our stakeholders makes sense.

**Considerations:**
- [ ]  Discuss potential approaches and technical factors before deciding on approach

* The present authoring experience is "manual" relying on HTML and changes must be made individually to the home page and to the /newsroom. 
* People familiar with Wordpress would expect using "Posts" or similar to manage the news item content
* Design system and ODI/CA standardized publishing method or framework may affect how to implement. Or the solution may be short lived as a bandaid.

![image](https://user-images.githubusercontent.com/85529382/133171410-0f704b80-a960-48bc-98d1-f5b7532dff92.png)
![image](https://user-images.githubusercontent.com/85529382/133171428-63b698a5-b584-4bd7-8c34-060f00539770.png)

**Comment by jaredwyee** [comment]
@thepegisin anything to add?

**Comment by jaredwyee** [comment]
@xjensen please work with @chachasikes team to determine how we might approach this for Drought, being mindful of global publishing approach

**Comment by xjensen** [comment]
@adam-little I wanted to get your opinion about how we should render the News page on Drought. Since I'm working on this now, it's a good time to implement changes. 

Here's the current Drought site.
<img width="857" alt="Screen Shot 2021-10-11 at 16 14 58" src="https://user-images.githubusercontent.com/1208960/136866112-79120d7b-a0c8-4998-91dd-7763fff7da56.png">

Here's what I found in Figma, in Design system components.
<img width="734" alt="Screen Shot 2021-10-11 at 16 15 45" src="https://user-images.githubusercontent.com/1208960/136866144-1e021e30-7a61-44fb-a1eb-9d3420a09534.png">

I'm wondering which of these is more recent and represents our ideal. I'm guessing Design System in Figma, but just wanted to confirm.

**Comment by thepegisin** [comment]
@jaredwyee - this feels ready to me. You can close this ticket, IMHO.

@chachasikes - yes, and we're tracking that in #197. I will note there to have you check my draft. TY!

**Comment by jaredwyee** [comment]
Great!
