### ISSUE TITLE
Pages don't have breadcrumbs

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#132]
In looking at the site with Adam today, we both noticed that there are no breadcrumbs at the top of pages. Navigational breadcrumbs are part of our CA Web Design System, as seen here on Cannabis:
![breadcrumbs](https://user-images.githubusercontent.com/63249920/135535459-a79b4213-ddc8-4efc-91e0-4becb2248d27.png)

**Comment by aaronhans** [comment]
We have some breadcrumbs in the headless cannabis templates, not the best way to do it but works for a v1 https://github.com/cagov/cannabis.ca.gov/blob/bd116012530d1ff9f478a3661e2f676fcf2024fb/pages/_includes/layouts/templates/page.njk#L8

Haven't figured out the best way to share templates between projects but the 11ty page templates would ideally be the same and reused...

**Comment by chachasikes** [comment]
Cannabis has breadcrumbs only because Wordpress was generating them and sending data to the API.

* That API data might not be available but it if it's there it should be labelled breadcrumb
* This isn't the solution we loved, and it can be improved.
* We were planning to use the menu api. Maybe we still can.
* The first two items are hard coded & should become configuration settings.

To think about:
* A breadcrumb data spec for the design system (vs. WordPress specific output and their specific hierarchy managment)
* breadcrumb-wordpress component option?

**Comment by aaronhans** [comment]
See if this is specific to cannabis, review priority assignment with Peggy
