### ISSUE TITLE
WordPress Sync Error

### ISSUE THREAD

**Issue by zakiya** [cagov/drought.ca.gov#306]
Reported vis Slackbot
<img width="728" alt="CleanShot 2022-08-03 at 14 15 24@2x" src="https://user-images.githubusercontent.com/915352/182713444-9cc85301-a0d4-4e43-8a97-1e2677db35d6.png">

Error: 422 error making request patch https://api.github.com/repos/cagov/drought.ca.gov/git/refs/heads/staging: "Unprocessable

**Comment by carterm** [comment]
Looks like a concurrency issue when updating the commit head because a more recent change was committed while an older one was still processing.  There were a lot of updates to the same file that happened around 11:22am.  The failure was overwritten pretty quickly with a subsequent update.  The version of `wordpress-to-github` used here uses the `github-api` which doesn't report the errors in these situations very well.

I recommend we just ignore it.

**Comment by xjensen** [comment]
Thanks, @carterm! Much appreciated.

I'm going to accept that peace of mind and close this issue.

**Comment by zakiya** [comment]
QQ: My memory is fuzzy about all the wp to gh work that was done last fall. I remember one of the tasks was to replace github-api with our own version. Do we have documentation about which sites are using which plugin?

**Comment by carterm** [comment]
There is a beta release that has interface changes and would require dev/test to implement.
https://www.npmjs.com/package/@cagov/wordpress-to-github/v/0.3.0
