### ISSUE TITLE
Social Media Tool Kit in Footer

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#69]
replace Governor's Newroom with "Social media sharing" using link https://saveourwater.com/en/Partner-Toolkit

**Comment by jbum** [comment]
@thepegisin - I believe this can be edited by editing the content-menu, where Governor's Newsroom appears.  

Subsequently, you will need to make a minor change to a post so the site rebuilds (you can use the sandbox-1 page for this purpose, since it is not a public page).

![image](https://user-images.githubusercontent.com/287977/135685040-b81f1e4f-8d89-4485-8d6c-48fbc0807fd3.png)

ALSO, I noticed the apostrophe in Governor's was a straight apostrophe rather than a curly quote. We're getting rid of that here, so it doesn't matter, but I'm curious what our policy is regarding that symbol... (should we be using a ’ instead of a ' for apostrophes?)

**Comment by kkoryaka** [comment]
@jaredwyee I am working in parallel on theme where editors will be able to add social media in WP options.

**Comment by chachasikes** [comment]
Context update:
* Jim found a menu that I initially created hoping this could connect to the front end.
* In grooming the WP Themes board, Konstantin shared that he is working on an update to the cagov GeneratePress theme to render this data to the menu
* Then Jon can help with connecting the menu item ("social") - to the menu item & 
* Then we can update the content (make sure it's correct) 
* And then we can remove the links from the odi-publishing config.json
(* And then request that the CAWeb theme include this behavior or add an API settings for the existing widget.)

This issue is also being tracked on the ODI Publishing WP Themes board
