### ISSUE TITLE
Design an Image Caption component

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#73]
We plan to show various images in our content (hero, content page) that convey drought conditions at certain locations on a certain date. In order to be informative and accurate in what we present, we want to include an information caption. Presently our design system does not have a "caption" component.

Example pages where a caption might exist:
https://drought.ca.gov/
https://drought.ca.gov/state-drought-response/

**Comment by adam-little** [comment]
For content pages and articles (e.g. Announcements), we have a caption style [in Figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=11%3A0).
![image](https://user-images.githubusercontent.com/69167298/126000976-b8f95aa9-4f5d-4e59-b19c-a520ad121387.png)

- Small text
- 8px spacing between image and caption

For homepage hero card, adding a caption will require some design updates to the card. I propose redesigning this to be a full width container instead of a card shape. Here is an example:
https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=11%3A0

@jaredwyee should we close this issue and make two separate issues for 1) image caption in posts and 2) redesigned hero card?

**Comment by adam-little** [comment]
@jaredwyee 

Here is issue for general caption style: https://github.com/cagov/drought.ca.gov/issues/73

Here is issue for hero card caption: https://github.com/cagov/cannabis.ca.gov/issues/261
