### ISSUE TITLE
Staging environment for Drought so that we can review changes safely before pushing to prod

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#90]

**Comment by jaredwyee** [comment]
@jbum  @aaronhans  fyi created this

**Comment by aaronhans** [comment]
Here are some assumptions we should review with the editorial team:

- Enabling proper WordPress preview so that clicking preview on any post or page will show a faithful rendering of the content exactly as it will appear in production is the top priority

This work is already underway. We plan to use the 11ty serverless plugin (https://www.11ty.dev/docs/plugins/serverless/). Carte is reviewing how to setup the pipeline that will receive the prompt from WordPress to render the latest draft version of a post. We will also need to install or build a plugin that reroutes the preview link to use this tool.

- Large changes or things that need to be sent out for approval need some other type of flow that lets change be viewed before they go live.

We can do this by duplicating the production pipeline starting with our pantheon staging instance. This will provide shareable links for content published from pantheon staging. Migrating this content to pantheon production would require engineering unless we figure out how to let editors control this part.

We can set this part of the pipeline up now and it will be useful because we have some disruptive changes to make to the site management like removing all the hardcoded HTML currently used to manage recent announcements.

**Comment by jaredwyee** [comment]
@aaronhans Would we have a general pattern how this process works for WP editing -> Staging -> prod going fwd? So checking in with content folks is how we would do it generically: Drought, Project, X, Project Y, etc. Correct?

**Comment by aaronhans** [comment]
Right now on the covid site editors can add a tag to a post like "staging" which will push that post only to that environment. We are going to verify with the editorial team but it seems like preserving this functionality is convenient because they won't have to deal with a separate WordPress environment. These capabilities should cover most editing workflows:
- Trust the preview link for immediate review during editing
- To push only to a staging if edits need to be shared for approval

In addition we have a development flow where we can modify WordPress code in dev/test live WordPress instances and migrate that to production. This can also be utilized for content changes and might be useful if major multi page rewrites are underway.

The visitor facing site is statically generated by 11ty so none of the WordPress code modifications get run when a page is viewed and we can spin up many preview environments based on different tags if desired.

**Comment by jaredwyee** [comment]
Sounds great, thanks for expounding further.

**Comment by jbum** [comment]
Is there remaining work to be done on this ticket?  @jaredwyee

**Comment by aaronhans** [comment]
Environments for drought are up and respecting staging tags on posts or pages: https://staging.drought.ca.gov/

**Comment by jaredwyee** [comment]
Noticed this discrepancy between prod and staging, where the Actions and News should be side by side. Is this something that needs to be fixed in code or somehow in WP/content post?

![image](https://user-images.githubusercontent.com/85529382/129249735-d14bd1df-8d28-48b0-9c72-0ee0abaadefa.png)
![image](https://user-images.githubusercontent.com/85529382/129249767-846db9ba-831c-4cc4-8fdd-402acd95fe8f.png)

**Comment by aaronhans** [comment]
Weird, there is some incorrect CSS in staging that is not present in production.

I need to create several tickets for drought to start inheriting all the CSS from the newly available design system modules. When I do this I will make sure the staging and main branches are in synch and this bug does not occur anywhere

**Comment by jbum** [comment]
Closing this, since the staging has been created. New tickets should be created for discrepencies.
